#!/usr/bin/env bun
/**
 * Release Notes Generator for TextSwift
 * Uses Claude API to generate release notes from git commits
 */

import Anthropic from "@anthropic-ai/sdk";
import { $ } from "bun";

const GIT_LOG_FORMAT = "--pretty=format:%h %s";

async function getCommitsSinceTag(tag?: string): Promise<string> {
  let commits = "";

  if (tag) {
    try {
      commits = await $`git log ${{ raw: `${tag}..HEAD` }} ${GIT_LOG_FORMAT}`.text();
    } catch {
      commits = "";
    }
  }

  if (!tag || !commits) {
    try {
      const tagsResult = await $`git tag --sort=-version:refname`.text();
      const tags = tagsResult.trim().split("\n").filter(t => t);

      if (tags.length >= 2) {
        commits = await $`git log ${{ raw: `${tags[1]}..HEAD` }} ${GIT_LOG_FORMAT}`.text();
      } else if (tags.length === 1) {
        commits = await $`git log ${GIT_LOG_FORMAT}`.text();
      } else {
        commits = await $`git log -50 ${GIT_LOG_FORMAT}`.text();
      }
    } catch {
      commits = await $`git log -50 ${GIT_LOG_FORMAT}`.text();
    }
  }

  return commits;
}

async function getChangedFiles(tag?: string): Promise<string> {
  let changedFiles = "";

  if (tag) {
    try {
      changedFiles = await $`git diff --name-status ${{ raw: `${tag}..HEAD` }}`.text();
    } catch {
      changedFiles = "";
    }
  }

  if (!tag || !changedFiles) {
    try {
      const tagsResult = await $`git tag --sort=-version:refname`.text();
      const tags = tagsResult.trim().split("\n").filter(t => t);

      if (tags.length >= 2) {
        changedFiles = await $`git diff --name-status ${{ raw: `${tags[1]}..HEAD` }}`.text();
      } else {
        changedFiles = await $`git diff --name-status HEAD~50..HEAD`.text();
      }
    } catch {
      changedFiles = await $`git diff --name-status HEAD~50..HEAD`.text();
    }
  }

  return changedFiles;
}

function buildPrompt(version: string, commits: string, changedFiles: string): string {
  return `You are a release notes writer for the TextSwift project.

## Project Info

TextSwift is a Chrome extension for instant in-page translation powered by Codex CLI.
Key components: Chrome Extension (content script, popup, service worker), Native Messaging Host, CLI setup tool.

## Release Version

${version}

## Commit History

\`\`\`
${commits.substring(0, 5000)}
\`\`\`

## Changed Files

\`\`\`
${changedFiles.substring(0, 3000)}
\`\`\`

## Writing Guidelines

1. **Categorize by Conventional Commits**:
   - 🚀 Features (feat:)
   - 🐛 Bug Fixes (fix:)
   - 📚 Documentation (docs:)
   - ♻️ Refactoring (refactor:)
   - 🔧 Chores (chore:)

2. **User-friendly descriptions**: Explain technical changes from the user's perspective

3. **Breaking Changes**: Highlight in a separate section if any

## Response Format (Markdown)

# Release v${version}

## Highlights

(1-3 key highlights of this release)

## 🚀 Features

- (new features)

## 🐛 Bug Fixes

- (bug fixes)

## 📚 Documentation

- (documentation changes)

## ♻️ Other Changes

- (other changes)

## ⚠️ Breaking Changes

(if none, omit this section)

## 📋 Full Changelog

(key commit summary)

---
_Release notes generated by Claude API._
`;
}

async function generateReleaseNotes(version?: string): Promise<string> {
  const releaseVersion = version || process.env.RELEASE_VERSION || "X.X.X";
  const previousTag = process.env.PREVIOUS_TAG;

  const commits = await getCommitsSinceTag(previousTag);
  const changedFiles = await getChangedFiles(previousTag);

  if (!commits.trim()) {
    return `⚠️ No commits found for v${releaseVersion}.`;
  }

  const client = new Anthropic({
    apiKey: process.env.ANTHROPIC_API_KEY,
  });

  const message = await client.messages.create({
    model: "claude-sonnet-4-5-20250929",
    max_tokens: 2048,
    messages: [
      {
        role: "user",
        content: buildPrompt(releaseVersion, commits, changedFiles),
      },
    ],
  });

  const resultParts: string[] = [];
  for (const block of message.content) {
    if (block.type === "text") {
      resultParts.push(block.text);
    }
  }

  return resultParts.join("\n");
}

// Main execution
if (import.meta.main) {
  const version = process.argv[2];

  try {
    const result = await generateReleaseNotes(version);
    console.log(result);
  } catch (error) {
    if (error instanceof Anthropic.APIError) {
      console.error(`⚠️ Claude API error: ${error.message}`);
      process.exit(1);
    } else {
      console.error(`⚠️ Unexpected error: ${error}`);
      process.exit(1);
    }
  }
}
